/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayana;

import Classes.ComboListener;
import Classes.Inventory_Category;
import Classes.Inventory_Type;
import Classes.Provider;
import Classes.Sale_Inventory;
import Classes.Save;
import Classes.Service_Type;
import Conexion.Conexion;
import java.awt.Image;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author macbook
 */
public class AddProduct extends javax.swing.JDialog {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
         setIconImage (new ImageIcon(getClass().getResource("Images/Screenshot_1.png")).getImage());
           ImageIcon imagen1 = new ImageIcon(getClass().getResource("Images/Guardar.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        btnAddInsumos.setIcon(fondo1);
        MontoProduct=0;
        CostProduct=0;
         try{
            con=new Conexion();
            con.Conectar();
            inventory_types=con.GetInventoryTypes();
            providers=con.GetRegProviders();
            inventory_category=con.GetInventoryCategory();
            con.Desconectar();
            }catch(Exception e){}finally{}
           
            for(Inventory_Category obj : inventory_category){
        vectorCategoria.add(obj.Description);
        }
             cbxCategory.setModel(new DefaultComboBoxModel(vectorCategoria));		
JTextField text1 = (JTextField)cbxCategory.getEditor().getEditorComponent();
		text1.setFocusable(true);
		text1.setText("");
		text1.addKeyListener(new ComboListener(cbxCategory,vectorCategoria));
   
                 for(Provider obj : providers){
        vectorProveedor.add(obj.Description);
        }
             cbxProvider.setModel(new DefaultComboBoxModel(vectorProveedor));		
JTextField text2 = (JTextField)cbxProvider.getEditor().getEditorComponent();
		text2.setFocusable(true);
		text2.setText("");
		text2.addKeyListener(new ComboListener(cbxProvider,vectorProveedor));
                
   if(Save.status2==1){
            this.setTitle("Editar producto");
             jLabel17.setText("Editar producto");
                   inventory_type= inventory_types.stream()
            .filter(obj -> Save.Product==obj.Id)
            .findAny()
            .orElse(null);
                   int cat=0;
                   for(Inventory_Category obj :inventory_category){
                       if(inventory_type.Category.equals(obj.Description)){
                           break;
                       }else{
                           cat+=1;
                       }
                   }
           int prov=0;
                   for(Provider obj :providers){
                       if(inventory_type.Provider.equals(obj.Description)){
                           break;
                       }else{
                           prov+=1;
                       }
                   }
             
            txtNombre.setText(inventory_type.Description);
            cbxCategory.setSelectedIndex(cat);
            nupCantidad.setValue(inventory_type.MinStock);
            cbxProvider.setSelectedIndex(prov);
            CostProduct=inventory_type.Cost;
            txtMontoProducto.setText(CostProduct+""); 
            MontoProduct=inventory_type.Price;
            txtPrecioproducto.setText(MontoProduct+"");        
   }
    }
double MontoProduct;
double CostProduct;

 Conexion con;
     DecimalFormat formatea;
    List<Inventory_Category> inventory_category;
    List<Provider> providers;
    Inventory_Type inventory_type;
List<Inventory_Type> inventory_types;
@SuppressWarnings("rawtypes")
Vector vectorProveedor = new Vector();
Vector vectorCategoria = new Vector();
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnAddInsumos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioproducto = new javax.swing.JTextField();
        txtMontoProducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbxProvider = new javax.swing.JComboBox<>();
        nupCantidad = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxCategory = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo producto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(217, 234, 220));
        jLabel17.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nuevo producto");

        btnAddInsumos.setBackground(new java.awt.Color(255, 255, 255));
        btnAddInsumos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        btnAddInsumos.setForeground(new java.awt.Color(55, 55, 55));
        btnAddInsumos.setText("Guardar");
        btnAddInsumos.setBorderPainted(false);
        btnAddInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInsumosActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 55, 55));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Precio de venta");

        txtPrecioproducto.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioproducto.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtPrecioproducto.setForeground(new java.awt.Color(55, 55, 55));
        txtPrecioproducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtPrecioproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioproductoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioproductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioproductoKeyReleased(evt);
            }
        });

        txtMontoProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtMontoProducto.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtMontoProducto.setForeground(new java.awt.Color(55, 55, 55));
        txtMontoProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtMontoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoProductoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMontoProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoProductoKeyReleased(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(55, 55, 55));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Costo del Proveedor");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(55, 55, 55));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Proveedor");

        cbxProvider.setBackground(new java.awt.Color(255, 255, 255));
        cbxProvider.setEditable(true);
        cbxProvider.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        cbxProvider.setForeground(new java.awt.Color(55, 55, 55));
        cbxProvider.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        cbxProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProviderActionPerformed(evt);
            }
        });

        nupCantidad.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        nupCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        nupCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        nupCantidad.setMinimumSize(new java.awt.Dimension(270, 0));
        nupCantidad.setName(""); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(55, 55, 55));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Cantidad mínima");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(55, 55, 55));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Categoría");

        cbxCategory.setBackground(new java.awt.Color(255, 255, 255));
        cbxCategory.setEditable(true);
        cbxCategory.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        cbxCategory.setForeground(new java.awt.Color(55, 55, 55));
        cbxCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        cbxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoryActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(55, 55, 55));
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(55, 55, 55));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nupCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nupCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnAddInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoProductoKeyTyped

    }//GEN-LAST:event_txtMontoProductoKeyTyped

    private void txtMontoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoProductoKeyPressed

    }//GEN-LAST:event_txtMontoProductoKeyPressed

    private void txtMontoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoProductoKeyReleased
        try {
            CostProduct = Double.parseDouble(txtMontoProducto.getText());
        } catch (NumberFormatException e) {
            CostProduct = 0;
            txtMontoProducto.setText(null);
        }
    }//GEN-LAST:event_txtMontoProductoKeyReleased

    private void btnAddInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInsumosActionPerformed
        try{
            if(txtNombre.getText().length()<1){
                return;
            }
Provider provider = providers.stream()
            .filter(obj -> cbxProvider.getSelectedItem().toString().equals(obj.Description))
            .findAny()
            .orElse(null);
Inventory_Category category = inventory_category.stream()
            .filter(obj -> cbxCategory.getSelectedItem().toString().equals(obj.Description))
            .findAny()
            .orElse(null);
            
            if(Integer.parseInt(nupCantidad.getValue().toString())>=0)
            {
                if(Save.status2==1){
                try{
                    con=new Conexion();
                    con.Conectar();
                   con.UpdateProduct(new Inventory_Type(Save.Product,txtNombre.getText(),CostProduct,MontoProduct,Integer.parseInt(nupCantidad.getValue().toString()),category.Id,1,provider.Id,0,0,0));
                    con.Desconectar();
                }catch (SQLException ex) {}
                con.Desconectar();
                    JOptionPane.showMessageDialog(this,"Producto modificado con éxito.");
            
                this.dispose();}
                else{
                try{
                    con=new Conexion();
                    con.Conectar();
                   con.AddProduct(new Inventory_Type(txtNombre.getText(),CostProduct,MontoProduct,Integer.parseInt(nupCantidad.getValue().toString()),category.Id,1,provider.Id,0,0,0));
                    con.Desconectar();
                }catch (SQLException ex) {}
                con.Desconectar();
                    JOptionPane.showMessageDialog(this,"Producto nuevo agregado con éxito.");
            
                this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this,"Error de guardado","Error de guardado",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            return;}finally{}
    }//GEN-LAST:event_btnAddInsumosActionPerformed

    private void cbxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoryActionPerformed

    }//GEN-LAST:event_cbxCategoryActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtPrecioproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioproductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioproductoKeyTyped

    private void txtPrecioproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioproductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioproductoKeyPressed

    private void txtPrecioproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioproductoKeyReleased
         try {
            MontoProduct = Double.parseDouble(txtPrecioproducto.getText());
        } catch (NumberFormatException e) {
            MontoProduct = 0;
            txtPrecioproducto.setText(null);
        }
    }//GEN-LAST:event_txtPrecioproductoKeyReleased

    private void cbxProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProviderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInsumos;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxProvider;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner nupCantidad;
    private javax.swing.JTextField txtMontoProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioproducto;
    // End of variables declaration//GEN-END:variables
}
