/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayana;

import Classes.Account;
import Classes.Client;
import Classes.ComboListener;
import Classes.Income;
import Classes.Save;
import static Classes.Save.Client;
import Conexion.Conexion;
import java.awt.Image;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author macbook
 */
public class AddPagoCliente extends javax.swing.JDialog {

    /**
     * Creates new form AddExpense
     */
    public AddPagoCliente() {
        initComponents();
        try{
         setIconImage (new ImageIcon(getClass().getResource("Images/Screenshot_1.png")).getImage());
   ImageIcon imagen = new ImageIcon(getClass().getResource("Images/Guardar.png"));
      Icon  fondo = new ImageIcon(imagen.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        btnCapturaEgresos.setIcon(fondo);
    txtProv.setText(Save.Providertext);
          con=new Conexion();
        con.Conectar();
          try {
        accounts=con.GetAccounts();
      client=con.GetClientById(Save.Client);
          DecimalFormat formatea = new DecimalFormat("$###,###.##");
      txtSaldo.setText(formatea.format(client.Saldo()));
          } catch (SQLException ex) {}     
        con.Desconectar();
        for(Account obj : accounts){
        vectorCuentaEgr.add(obj.Description);
        }
                 cbxCuentaEgresos.setModel(new DefaultComboBoxModel(vectorCuentaEgr));		
JTextField text4 = (JTextField)cbxCuentaEgresos.getEditor().getEditorComponent();
		text4.setFocusable(true);
		text4.setText("");
		text4.addKeyListener(new ComboListener(cbxCuentaEgresos,vectorCuentaEgr));
                 dtEgresos.getDateEditor().setEnabled(false);
                dtEgresos.setDate(Date.valueOf(LocalDate.now()));
        }catch(Exception e){
              JOptionPane.showMessageDialog(this,"Error de conexión.");
        }finally{}
    }
Vector vectorCuentaEgr = new Vector();
List<Account> accounts;
Conexion con;
Client client;
double MontoEgr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtDescripcionEgresos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtProv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFacturaEgresos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tbFacturaEgresos = new javax.swing.JToggleButton();
        txtMontoEgresos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxCuentaEgresos = new javax.swing.JComboBox<>();
        dtEgresos = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnCapturaEgresos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar pago");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(55, 55, 55));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Saldo");

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldo.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(55, 55, 55));
        txtSaldo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtSaldo.setEnabled(false);

        txtDescripcionEgresos.setBackground(new java.awt.Color(255, 248, 245));
        txtDescripcionEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtDescripcionEgresos.setForeground(new java.awt.Color(55, 55, 55));
        txtDescripcionEgresos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(55, 55, 55));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Cliente");

        txtProv.setEditable(false);
        txtProv.setBackground(new java.awt.Color(255, 255, 255));
        txtProv.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtProv.setForeground(new java.awt.Color(55, 55, 55));
        txtProv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtProv.setEnabled(false);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(55, 55, 55));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Monto");

        txtFacturaEgresos.setBackground(new java.awt.Color(255, 248, 245));
        txtFacturaEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtFacturaEgresos.setForeground(new java.awt.Color(55, 55, 55));
        txtFacturaEgresos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtFacturaEgresos.setEnabled(false);
        txtFacturaEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaEgresosActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(55, 55, 55));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Factura");

        tbFacturaEgresos.setBackground(new java.awt.Color(255, 248, 245));
        tbFacturaEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        tbFacturaEgresos.setForeground(new java.awt.Color(55, 55, 55));
        tbFacturaEgresos.setSelected(true);
        tbFacturaEgresos.setText("Si");
        tbFacturaEgresos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        tbFacturaEgresos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbFacturaEgresosStateChanged(evt);
            }
        });
        tbFacturaEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFacturaEgresosActionPerformed(evt);
            }
        });

        txtMontoEgresos.setBackground(new java.awt.Color(255, 248, 245));
        txtMontoEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        txtMontoEgresos.setForeground(new java.awt.Color(55, 55, 55));
        txtMontoEgresos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtMontoEgresos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoEgresosKeyReleased(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(55, 55, 55));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Cuenta");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 55, 55));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Fecha");

        cbxCuentaEgresos.setBackground(new java.awt.Color(255, 248, 245));
        cbxCuentaEgresos.setEditable(true);
        cbxCuentaEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        cbxCuentaEgresos.setForeground(new java.awt.Color(55, 55, 55));
        cbxCuentaEgresos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        cbxCuentaEgresos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCuentaEgresosItemStateChanged(evt);
            }
        });
        cbxCuentaEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCuentaEgresosActionPerformed(evt);
            }
        });

        dtEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 55, 55));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Detalle");

        btnCapturaEgresos.setBackground(new java.awt.Color(255, 255, 255));
        btnCapturaEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        btnCapturaEgresos.setForeground(new java.awt.Color(55, 55, 55));
        btnCapturaEgresos.setText("Guardar");
        btnCapturaEgresos.setToolTipText("");
        btnCapturaEgresos.setBorder(null);
        btnCapturaEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaEgresosActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(217, 234, 220));
        jLabel11.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar pago de cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProv, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtMontoEgresos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dtEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCuentaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tbFacturaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacturaEgresos)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnCapturaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCuentaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbFacturaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFacturaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnCapturaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapturaEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaEgresosActionPerformed
        try{
            Account cuenta= accounts.stream()
            .filter(obj -> cbxCuentaEgresos.getSelectedItem().toString().equals(obj.Description))
            .findAny()
            .orElse(null);

            if(MontoEgr==0){
                JOptionPane.showMessageDialog(this,"Falta ingresar monto.");
                return;
            }
            int fac=0;
            if(tbFacturaEgresos.isSelected()){
                fac=1;
            }
            con=new Conexion();
            con.Conectar();
            con.AddIncome(new Income(dtEgresos.getDate(),Save.Client,1,txtDescripcionEgresos.getText(),cuenta.Id,fac,txtFacturaEgresos.getText(),MontoEgr));
            con.Desconectar();
            JOptionPane.showMessageDialog(this,"Pago capturado con éxito.");
            this.dispose();
            MontoEgr=0;
            txtDescripcionEgresos.setText(null);
            txtMontoEgresos.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Información faltante.");
        }finally{}
    }//GEN-LAST:event_btnCapturaEgresosActionPerformed

    private void cbxCuentaEgresosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCuentaEgresosItemStateChanged

    }//GEN-LAST:event_cbxCuentaEgresosItemStateChanged

    private void cbxCuentaEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCuentaEgresosActionPerformed

    }//GEN-LAST:event_cbxCuentaEgresosActionPerformed

    private void txtMontoEgresosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoEgresosKeyReleased
        try {
            MontoEgr = Double.parseDouble(txtMontoEgresos.getText());
        } catch (NumberFormatException e) {
            MontoEgr = 0;
            txtMontoEgresos.setText(null);
        }
    }//GEN-LAST:event_txtMontoEgresosKeyReleased

    private void tbFacturaEgresosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbFacturaEgresosStateChanged

    }//GEN-LAST:event_tbFacturaEgresosStateChanged

    private void tbFacturaEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFacturaEgresosActionPerformed
        if(tbFacturaEgresos.isSelected()){
            tbFacturaEgresos.setText("Si");
            txtFacturaEgresos.setEditable(true);
        }else{
            tbFacturaEgresos.setText("No");
            txtFacturaEgresos.setText(null);
            txtFacturaEgresos.setEditable(false);
        }
    }//GEN-LAST:event_tbFacturaEgresosActionPerformed

    private void txtFacturaEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaEgresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaEgresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPagoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPagoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPagoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPagoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPagoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturaEgresos;
    private javax.swing.JComboBox<String> cbxCuentaEgresos;
    private com.toedter.calendar.JDateChooser dtEgresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton tbFacturaEgresos;
    private javax.swing.JTextField txtDescripcionEgresos;
    private javax.swing.JTextField txtFacturaEgresos;
    private javax.swing.JTextField txtMontoEgresos;
    private javax.swing.JTextField txtProv;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
