/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magstone;

import Adicional.CreatePDF;
import Adicional.ExportExc;
import Classes.ComboListener;
import Classes.Inventory_Type;
import Classes.Moves_Account;
import Classes.Sale_Inventory;
import Classes.Save;
import Classes.Tickets;
import Classes.Tickets_Contains;
import Conexion.Conexion;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbook
 */
public class TIckets extends javax.swing.JDialog {

    /**
     * Creates new form TIckets
     */
    public TIckets() {
        initComponents();
        jLabel5.setText("Tickets de "+Save.Sale2.Description);
       ImageIcon imagen1 = new ImageIcon(getClass().getResource("Images/Eliminar.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        btnEliminar.setIcon(fondo1);
        btnEliminar1.setIcon(fondo1);
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("Images/Agregar.png"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        btnGenTicket.setIcon(fondo3);
            try{
                con=new Conexion();
                con.Conectar();
              list=con.GetTickets(Save.Sale2.Id); //con.AddSaleInventory(new Sale_Inventory(0,producto.Id,Save.Sale2.Id,Integer.parseInt(nupCantidad.getValue().toString()),MontoProduct,0));
          inventory_types=con.GetInventoryTypes();
              con.Desconectar();
            }catch (SQLException ex) {}
         
       table.getTableHeader().setBackground(Color.white);
        table.getTableHeader().setForeground(Color.black);
        table.getTableHeader().setFont(new Font("InaiMathi", 0, 18)); 
         table.getColumnModel().getColumn(2).setCellRenderer(new TimestampCellRenderer());
         DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
         tcr.setHorizontalAlignment(JLabel.CENTER);
           table.getColumnModel().getColumn(1).setCellRenderer(tcr);
            model=(DefaultTableModel)table.getModel();
               model1=(DefaultTableModel)table1.getModel();
                  model2=(DefaultTableModel)tableAux.getModel();
         for(Tickets obj: list)
        {
            model.addRow(new Object[]{obj.Id,obj.Ticket_Num,obj.Date,obj.Comentario,obj.Chofer});
        }
         for(Inventory_Type obj : inventory_types){
        vectorProveedor.add(obj.Description);
        }
         listaux=new ArrayList<Tickets_Contains>();
             cbxProducto.setModel(new DefaultComboBoxModel(vectorProveedor));		
JTextField text2 = (JTextField)cbxProducto.getEditor().getEditorComponent();
		text2.setFocusable(true);
		text2.setText("");
		text2.addKeyListener(new ComboListener(cbxProducto,vectorProveedor));
          }
    List<Tickets_Contains> listaux;
     List<Tickets> list;
      List<Tickets_Contains> list1;
      Vector vectorProveedor = new Vector();
 Conexion con;
 List<Inventory_Type> inventory_types;
   private DefaultTableModel model;
     private DefaultTableModel model2;
      private DefaultTableModel model1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPopupMenu();
        btnGenTicket = new javax.swing.JMenuItem();
        btnEliminar = new javax.swing.JMenuItem();
        Menu1 = new javax.swing.JPopupMenu();
        btnEliminar1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nupCantidad = new javax.swing.JSpinner();
        Contacto = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<>();
        btnNuevoCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAux = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        dtDate = new com.toedter.calendar.JDateChooser();
        txtChofer = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnNuevoCliente1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        btnGenTicket.setText("Generar ticket");
        btnGenTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenTicketActionPerformed(evt);
            }
        });
        Menu.add(btnGenTicket);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        Menu.add(btnEliminar);

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        Menu1.add(btnEliminar1);

        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nupCantidad.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        nupCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        nupCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        nupCantidad.setMinimumSize(new java.awt.Dimension(270, 0));
        nupCantidad.setName(""); // NOI18N
        nupCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nupCantidadStateChanged(evt);
            }
        });

        Contacto.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        Contacto.setForeground(new java.awt.Color(102, 102, 102));
        Contacto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Contacto.setText("Cantidad");

        cbxProducto.setBackground(new java.awt.Color(245, 245, 245));
        cbxProducto.setEditable(true);
        cbxProducto.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        cbxProducto.setForeground(new java.awt.Color(102, 102, 102));
        cbxProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        cbxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoActionPerformed(evt);
            }
        });

        btnNuevoCliente.setBackground(new java.awt.Color(217, 234, 220));
        btnNuevoCliente.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(51, 51, 51));
        btnNuevoCliente.setText("Agregar nuevo ticket");
        btnNuevoCliente.setToolTipText("");
        btnNuevoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 146, 147)));
        btnNuevoCliente.setFocusTraversalPolicyProvider(true);
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        tableAux.setBackground(new java.awt.Color(245, 245, 245));
        tableAux.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableAux.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        tableAux.setForeground(new java.awt.Color(0, 0, 0));
        tableAux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Producto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAux.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tableAux.setColumnSelectionAllowed(true);
        tableAux.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableAux.setFocusTraversalKeysEnabled(false);
        tableAux.setFocusable(false);
        tableAux.setGridColor(new java.awt.Color(153, 153, 153));
        tableAux.setRowHeight(22);
        tableAux.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tableAux.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableAux.setShowGrid(true);
        tableAux.getTableHeader().setReorderingAllowed(false);
        tableAux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableAuxMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tableAux);
        tableAux.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tableAux.getColumnModel().getColumnCount() > 0) {
            tableAux.getColumnModel().getColumn(0).setMinWidth(0);
            tableAux.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableAux.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel11.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Producto");

        dtDate.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N

        txtChofer.setBackground(new java.awt.Color(245, 245, 245));
        txtChofer.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        txtChofer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        txtChofer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChoferKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChoferKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChoferKeyReleased(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nuevo ticket");
        jLabel19.setToolTipText("");

        txtComentarios.setBackground(new java.awt.Color(245, 245, 245));
        txtComentarios.setColumns(20);
        txtComentarios.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        txtComentarios.setRows(5);
        txtComentarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jScrollPane4.setViewportView(txtComentarios);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Comentario");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("Chofer");

        btnNuevoCliente1.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente1.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        btnNuevoCliente1.setForeground(new java.awt.Color(51, 51, 51));
        btnNuevoCliente1.setText("Agregar producto");
        btnNuevoCliente1.setToolTipText("");
        btnNuevoCliente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 146, 147)));
        btnNuevoCliente1.setFocusTraversalPolicyProvider(true);
        btnNuevoCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCliente1ActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("Fecha");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nupCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChofer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nupCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tickets");
        jLabel5.setToolTipText("");

        table.setBackground(new java.awt.Color(245, 245, 245));
        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        table.setForeground(new java.awt.Color(0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Folio", "Fecha", "Comentario", "Chofer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        table.setColumnSelectionAllowed(true);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setFocusTraversalKeysEnabled(false);
        table.setFocusable(false);
        table.setGridColor(new java.awt.Color(153, 153, 153));
        table.setRowHeight(22);
        table.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        table.setShowGrid(true);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(0);
            table.getColumnModel().getColumn(0).setPreferredWidth(0);
            table.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        table1.setBackground(new java.awt.Color(245, 245, 245));
        table1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table1.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        table1.setForeground(new java.awt.Color(0, 0, 0));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Producto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        table1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table1.setFocusTraversalKeysEnabled(false);
        table1.setFocusable(false);
        table1.setGridColor(new java.awt.Color(153, 153, 153));
        table1.setRowHeight(22);
        table1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        table1.setShowGrid(true);
        table1.getTableHeader().setReorderingAllowed(false);
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table1MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table1);
        table1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setMinWidth(0);
            table1.getColumnModel().getColumn(0).setPreferredWidth(0);
            table1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
  try{
if(listaux.size()==0){
    return;
}
                try{
                con=new Conexion();
                con.Conectar();
              con.AddTickets(new Tickets(0,dtDate.getDate(),Save.Sale2.Id,txtComentarios.getText(),txtChofer.getText(),0), listaux);  
              list=con.GetTickets(Save.Sale2.Id);
              con.Desconectar();}catch (SQLException ex) {}     
        con.Desconectar();
                 JOptionPane.showMessageDialog(this,"Ticket generado con éxito.");
   listaux.clear();
    int j=model2.getRowCount();
        for(int i=0;i<j;i++){
            model2.removeRow(j-i-1);
        }
     j=model.getRowCount();
        for(int i=0;i<j;i++){
            model.removeRow(j-i-1);
        }
         for(Tickets obj: list)
        {
            model.addRow(new Object[]{obj.Id,obj.Ticket_Num,obj.Date,obj.Comentario,obj.Chofer});
        }
        }catch(Exception e){
            
       }finally{}
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
   if (evt.getClickCount() == 2 && !evt.isConsumed()) {
        evt.consume();
        Menu.show(table, evt.getX(), evt.getY());
        }    
    }//GEN-LAST:event_tableMouseReleased

    private void nupCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nupCantidadStateChanged

    }//GEN-LAST:event_nupCantidadStateChanged

    private void cbxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoActionPerformed

    }//GEN-LAST:event_cbxProductoActionPerformed

    private void table1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseReleased
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
        evt.consume();
        Menu1.show(table1, evt.getX(), evt.getY());
        }    
    }//GEN-LAST:event_table1MouseReleased

    private void tableAuxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAuxMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAuxMouseReleased

    private void txtChoferKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChoferKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChoferKeyTyped

    private void txtChoferKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChoferKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChoferKeyPressed

    private void txtChoferKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChoferKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChoferKeyReleased

    private void btnNuevoCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCliente1ActionPerformed
        try{

            Inventory_Type producto = inventory_types.stream()
            .filter(obj -> cbxProducto.getSelectedItem().toString().equals(obj.Description))            
            .findAny()
            .orElse(null);
            producto=inventory_types.get(cbxProducto.getSelectedIndex());

              listaux.add(new Tickets_Contains(0,producto.Id,Integer.parseInt(nupCantidad.getValue().toString()),0));
model2.addRow(new Object[]{producto.Id,producto.Description,Integer.parseInt(nupCantidad.getValue().toString())});
        }catch(Exception e){
               JOptionPane.showMessageDialog(this,"Error de conexión.","Error",JOptionPane.ERROR_MESSAGE);
       }finally{}
    }//GEN-LAST:event_btnNuevoCliente1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
     int j=model1.getRowCount();
        for(int i=0;i<j;i++){
            model1.removeRow(j-i-1);
        }
        if(table.getSelectedRow()>=0){
         for(Tickets_Contains obj :  list.get(table.getSelectedRow()).list){
                  model1.addRow(new Object[]{obj.Id,obj.Product,obj.Cantidad});
         }
       }
    }//GEN-LAST:event_tableMouseClicked

    private void btnGenTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenTicketActionPerformed
        Tickets producto = list.stream()
            .filter(obj -> Integer.parseInt( table.getValueAt(table.getSelectedRow(), 0).toString())==obj.Id)            
            .findAny()
            .orElse(null);
//          ExportExc xx=new ExportExc();
//        try {
//            xx.exportarTicket(producto);
        CreatePDF a=new CreatePDF();
         a.TicketVentas(producto);       
//        } catch (IOException ex) {
//            Logger.getLogger(TIckets.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnGenTicketActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int n = JOptionPane.showConfirmDialog(this,
            "¿Desea eliminar el ticket "+ table.getValueAt(table.getSelectedRow(), 1).toString() +"?","Confirmación",
            JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){

            con=new Conexion();
            con.Conectar();
            try{
                con.DeleteTicket(Integer.parseInt( table.getValueAt(table.getSelectedRow(), 0).toString()));
                  list=con.GetTickets(Save.Sale2.Id); //con.AddSaleInventory(new Sale_Inventory(0,producto.Id,Save.Sale2.Id,Integer.parseInt(nupCantidad.getValue().toString()),MontoProduct,0));
            } catch (SQLException ex) {
            }
            con.Desconectar();
            JOptionPane.showMessageDialog(this,"Ticket eliminado con éxito.");

            int j=model.getRowCount();
            for(int i=0;i<j;i++){
                model.removeRow(j-i-1);
            }
            for(Tickets obj: list)
        {
            model.addRow(new Object[]{obj.Id,obj.Ticket_Num,obj.Date,obj.Comentario,obj.Chofer});
        }
              j=model1.getRowCount();
            for(int i=0;i<j;i++){
                model1.removeRow(j-i-1);
            }
        } 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
      int n = JOptionPane.showConfirmDialog(this,
            "¿Desea eliminar el producto "+ table.getValueAt(table.getSelectedRow(), 1).toString() +"?","Confirmación",
            JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){

            con=new Conexion();
            con.Conectar();
            try{
                con.DeleteTicketContains2(Integer.parseInt( table1.getValueAt(table1.getSelectedRow(), 0).toString()));
                  list=con.GetTickets(Save.Sale2.Id); //con.AddSaleInventory(new Sale_Inventory(0,producto.Id,Save.Sale2.Id,Integer.parseInt(nupCantidad.getValue().toString()),MontoProduct,0));
            } catch (SQLException ex) {
            }
            con.Desconectar();
            JOptionPane.showMessageDialog(this,"liminado con éxito.");

            int j=model.getRowCount();
            for(int i=0;i<j;i++){
                model.removeRow(j-i-1);
            }
            for(Tickets obj: list)
        {
            model.addRow(new Object[]{obj.Id,obj.Ticket_Num,obj.Date,obj.Comentario,obj.Chofer});
        }
              j=model1.getRowCount();
            for(int i=0;i<j;i++){
                model1.removeRow(j-i-1);
            }
        } 
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIckets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contacto;
    private javax.swing.JPopupMenu Menu;
    private javax.swing.JPopupMenu Menu1;
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JMenuItem btnEliminar1;
    private javax.swing.JMenuItem btnGenTicket;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoCliente1;
    private javax.swing.JComboBox<String> cbxProducto;
    private com.toedter.calendar.JDateChooser dtDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner nupCantidad;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTable tableAux;
    private javax.swing.JTextField txtChofer;
    private javax.swing.JTextArea txtComentarios;
    // End of variables declaration//GEN-END:variables
}
